### ISSUE TITLE
As an editor, I want to define a set of annotations to be included in the document

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#1]
I want to:
- [x] See all annotations on a document
- [x] Filter annotations by:
  - [x] Who made them (which group of people)
  - [x] Tag (user-created taxonomies)
  - [x] Category (admin-created taxonomies)
- [x] Save the filtered set to be used for the edition

**Comment by SteveMarvin** [comment]
Regression: Saved filters are saved, but not applied properly. See #100.
