### ISSUE TITLE
Filter button present, but no filters

### ISSUE THREAD

**Issue by SteveMarvin** [performant-software/Annotation-Studio#101]
When in snapshot preview, the filter button is present, and the filters pane will open when it is clicked, but the pane is empty.

![image](https://cloud.githubusercontent.com/assets/18423533/21153443/80268ff6-c138-11e6-9e51-282efdf6ce4c.png)

**Comment by jamiefolsom** [comment]
Good point -- shouldn't be there.

**Comment by jamiefolsom** [comment]
This should be fixed, but is not urgent.
