### ISSUE TITLE
Uploaded docs never convert

### ISSUE THREAD

**Issue by SteveMarvin** [performant-software/Annotation-Studio#102]
When uploading a document in any format, and attempting to open the document for annotation, the document is never converted. Pasting the text in works fine.

![image](https://cloud.githubusercontent.com/assets/18423533/21153704/a3f889d8-c139-11e6-9212-0100c266b42b.png)

**Comment by jamiefolsom** [comment]
Assuming this is on production -- should now be corrected. Can you confirm?

**Comment by SteveMarvin** [comment]
It does indeed work now. Issue #59 is still occurring, but that may not be something we wish to fix. 👍
