### ISSUE TITLE
Usernames not imported along with email for COVE-originated annotations

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#106]
User field (with an email value) is copied over. Username, which should be Full Name, is not.

**Comment by jamiefolsom** [comment]
Fixed on Studio (and on Editions dev, where snapshots live). 

### How to test
1. Go to http://studio.covecollective.org/
1. Log in and view a document
1. Open right sidebar and click preview
1. Click "View on COVE"
1. Note that annotations, when clicked, now show full User names.

**Comment by SteveMarvin** [comment]
They do indeed, but I do not see the email anywhere. Was it desired that both be shown, or just teh username?

According to the test plan, no email is required, so I am accepting this for now.
