### ISSUE TITLE
Redirect to COVE HTML, not XML

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#109]
From document view link in AS

**Comment by SteveMarvin** [comment]
Assuming that this issue has to do with displaying XML document tree instead of HTML after coping to Editions and clicking View Now, or after clicking View in Editions, then this is not fixed. I am still seeing the XML document tree.

**Comment by SteveMarvin** [comment]
Well, darn it, now it appears to be working properly. At first I saw the XML tree, but when I came back after writing up the issue comment, it had moved on to show me a nicely formatted HTML page.
