### ISSUE TITLE
Make the class ("Edition") filter the default for all edition documents.

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#112]
### How to test

1. Visit http://studio.covecollective.org/documents/heart-of-darkness-part-ii or any other document assigned to the "editors" or "annotators" edition groups.
1. Note that all annotations by all members of those groups are visible once the document is loaded.

**Comment by SteveMarvin** [comment]
Hard for me to know how many there should be, but I do see multiple annotations by two different users. Tentatively 👍
