### ISSUE TITLE
Error on Preview

### ISSUE THREAD

**Issue by SteveMarvin** [performant-software/Annotation-Studio#113]
Hitting Preview button throws error. 

![preview](https://cloud.githubusercontent.com/assets/18423533/21431008/9a452c10-c833-11e6-888e-80303bbaebcf.png)

No apparent issue when viewing the preview, but hitting the Copy to Cove Editions button then throws an unusually spartan "We're sorry..." error. 

![screen shot 2016-12-22 at 10 46 09 am](https://cloud.githubusercontent.com/assets/18423533/21431077/e40d9850-c833-11e6-922a-465a4d78210a.png)

**Comment by jamiefolsom** [comment]
Hm. That's new. Could be because there's an effort underway to deploy COVE Editions too (the other site, to which the copy happens).

 Thanks, I will investigate.

**Comment by daverett** [comment]
This could very well be on my end. Let me check before you waste your time @jamiefolsom , and I'll report back.

**Comment by daverett** [comment]
Looks like things are still good at COVE Editions. Just successfully created an Editions document via a POST request.

**Comment by jamiefolsom** [comment]
Hi @daverett, to be clear, COVE Studio on both staging and production are using:
```
COVE_URL="http://dev-rc-distro.pantheonsite.io"
COVE_USERNAME="Test Annotator"
```
Is that what you're using? Thanks.

**Comment by jamiefolsom** [comment]
The error we're getting is `403 Forbidden`

**Comment by daverett** [comment]
Okay, I see. I keep thinking that you are POSTing as an administrator user, which Test Annotator is not. I have recently locked out users of non-admin roles from editing or adding "Editions" content, since all that content should be coming from COVE Studio. I can either upgrade the Test Annotator's permissions role or perhaps you could use the "M Folsom" user at COVE Editions, for which I'm guessing you have a pw, to do the posting. That user is an admin. I'd slightly prefer the latter if it's not too much trouble, since I'm actively using the Test Annotator user for permissions-related user testing. If it is, no problem upgrading Test Annotator.

**Comment by jamiefolsom** [comment]
No problem -- I'll use my account -- I the login username is `jamiefolsom`, actually, although the display name is "M Folsom" -- which should I use? Thanks.

**Comment by jamiefolsom** [comment]
OK, `M Folsom` returns `403` too, so I tried `jamiefolsom`, and now I get `406 not acceptable`.

**Comment by daverett** [comment]
Yep, missed the difference there. Thanks for figuring that out.

**Comment by daverett** [comment]
Hmm. That will require me to do some looking, since it doesn't make sense to me that if I can post as admin, which I just did, and jamiefolsom has the same permissions, how that wouldn't work.

**Comment by jamiefolsom** [comment]
Possible that there are required fields missing in the POST request, as discussed in our email convo? Of course, those would be new requirements, or else different permissions for `Test Annotator` vs. `jamiefolsom`, since it's been working using the former up to this point.

**Comment by jamiefolsom** [comment]
Do I recall correctly from the last time we went through this that admins actually didn't have permission to create documents?

**Comment by daverett** [comment]
User jamiefolsom has carte-blanche access to do absolutely everything just as admin has, so that should be an issue. Still looking.

**Comment by daverett** [comment]
I just successfully posted a document from a different account that I upgraded to the same permissions as jamiefolsom, so I'm thinking roles and permissions may not be the issue. Are you getting back tokens when trying to POST as jamiefolsom to indicate you are getting logged in successfully?

**Comment by jamiefolsom** [comment]
OK, I'll look into it in a bit. Thanks.
