### ISSUE TITLE
Scansion!

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#118]
From Dino's La Pietra group -- poetic scansion should be possible.

**Comment by daverett** [comment]
There is already this tool: http://prosody.lib.virginia.edu/. Authored by Herbert Tucker at UVA; he's involved in one of the COVE Editions, I believe. Looks like the source code is here: https://github.com/waynegraham/for_better_for_verse. Its texts are TEI, but I'm not sure how instrumental that markup is to the functionality.

**Comment by jamiefolsom** [comment]
@daverett very cool! I wonder if any of that could be ported to COVE Studio. Thanks!
