### ISSUE TITLE
Sanitize annotation text

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#137]
### What this solution does

- Strips out all formatting apart from line breaks and some minor punctuation, bullets, etc, from content pasted into both annotations and documents.

### How to test

- Go to http://studio.covecollective.org/ and log in (reset pw here if you need to: http://studio.covecollective.org/users/password/new)
- Create a new document: http://studio.covecollective.org/documents/new
- Paste content in from a word document; should have formatting stripped
- Set the document to annotatable.
- Go to the document and annotate it
- Paste content into the annotation from a word doc; formatting should be stripped

**Comment by SteveMarvin** [comment]
Looks like everything except Word comments are stripped.

**Comment by jamiefolsom** [comment]
Hey @SteveMarvin -- can you shoot me a link to the document with the annotation that contains a word comment? Thanks!

**Comment by jamiefolsom** [comment]
Also, is the word comment issue only on annotations?

**Comment by SteveMarvin** [comment]
http://studio.covecollective.org/documents/test-document-d59f3736-d53b-42ac-bdaf-8e9ed342ced5

Hmm, will you be able to see it? I'm not sure how to turn a document of mine into a Shared doc...

**Comment by SteveMarvin** [comment]
Yes, the comment does NOT show up when I am pasting content into the body of the document, it only shows up when I paste commented text into the annotation window.
