### ISSUE TITLE
Point covecollective.org to COVE Editions

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#139]

**Comment by daverett** [comment]
This had been already set up in Pantheon, at least partially. Here's some info that Pantheon dashboard tells me:

![screen shot 2017-10-27 at 11 39 09 am](https://user-images.githubusercontent.com/6519260/32112639-caf85d70-bb0b-11e7-9fb4-bcbb150a7379.png)

Not sure about the error below at the moment.
