### ISSUE TITLE
As a NAVSA member I want to sign into navsa.org, and get access to covecollective.org

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#14]
## How to test:

**Assumptions:**
* You have an account on navsa.org, using an email address that's not yet associated with an account on http://dev-rc-distro.pantheonsite.io (if not, ask me to set that up for you).

**Steps:**
1. If you're logged in to navsa.org with an account other than the one mentioned above, go there and log out.
2. Go to http://dev-rc-distro.pantheonsite.io and click log in, and wait for login to complete
3. If you're logged into navsa.org with the correct account, you'll now be logged into http://dev-rc-distro.pantheonsite.io, if you're not yet logged in, you'll be prompted to log in to navsa.org, then redirected to http://dev-rc-distro.pantheonsite.io and logged in.

**Background:**
- navsa.org is a wordpress site -- it would be the OAuth provider in this case.
- covecollective.org is a drupal site on pantheon.io -- it would be a client.
- accounts already exist in both places -- can we offer a "Sign in with navsa account" option?
- ~Wildcard cert for covecollective.org has been purchased -- need to verify same cert can be used with studio.covecollective.org as well (Rails app on heroku).~
- Related to #62
- @akstuhl is going to lead on this; @daverett can help

**Comment by SteveMarvin** [comment]
Magnificent! 👍
