### ISSUE TITLE
Filters not consistently including matches

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#142]
### Expected behavior:

- In cove editions, when you add a value to the category filter, all highlights that match that value are outlined in green, and all others are rendered in gray.

### Observed behavior

- Adding the "intepretative" category filter value to https://editions.covecollective.org/edition/portrait-wordsworth-br-haydon/portrait-wordsworth results in the phrase "=wind" not being outlined, but rather grayed out.

<img width="1074" alt="screenshot 2017-11-08 14 24 26" src="https://user-images.githubusercontent.com/882377/32570055-fa84b5a0-c490-11e7-854f-cd76183ae467.png">

- As seen in this screenshot of COVE Studio, that word is annotated with a category of "interpretative".

<img width="1124" alt="screenshot 2017-11-08 14 28 51" src="https://user-images.githubusercontent.com/882377/32570122-2c52d404-c491-11e7-9c1d-f6d1a3dde87e.png">

**Comment by tezcatlipoca** [comment]
Have a look at this - I changed the way we find the annotation matches:
https://dev-rc-distro.pantheonsite.io/edition/portrait-wordsworth-br-haydon/portrait-wordsworth

**Comment by SteveMarvin** [comment]
Jamie and I had a talk and this issue is clearly intended to provide verification of a very narrowly focused objective, in which it succeeds. ;-) 👍
