### ISSUE TITLE
Make the interface for switching annotators easier for copy-editors

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#152]
Filter user list by current document edition group. Also, there's at least one instance of an admin user not showing in the menu up on production. @timdunn22 -- I will share the email address with you -- see if you can find out why not.

**Comment by jamiefolsom** [comment]
For the `acts_as_taggable_on` edition (AKA group) tags assigned to the current document, filter the list of available admin users to switch to, by excluding all users who don't have one of those tags assigned to their user object. `User.tagged_with([array, of, values])`

**Comment by timdunn22** [comment]
# Time Estimate 
2 hours

**Comment by timdunn22** [comment]
# Testing 
1. Login
2. Go to http://cove-staging.herokuapp.com/documents/new-machine-stops
3. See if you are able to choose a user under the remember me dropdown ordered by first name and that these users are assigned to the document.

**Comment by jamiefolsom** [comment]
Move test plan to PR (#211).
