### ISSUE TITLE
Anthology Builder

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#157]
### What this feature does
Create a new “Anthology Builder”, including the following features:
- Search of existing documents by author, title, publication date, or other existing metadata.
- Bulk selection of a set of documents for addition to an anthology.
- Saving the anthology with a unique name and URL.
- An anthology page containing a list of the included documents.
- Documents in the anthology can be reused in other anthologies, and accessed by their anthology-specific URL (which will effectively filter annotations).

#### To create an anthology:

1. Login to your account at http://cove-staging.herokuapp.com/ (if it doesn't load at first, let Tim/Jamie know and we can restart it)
2. Under the anthologies menu click on create new anthology
3. Choose a unique name for your anthology and a description along with a banner image that is either a .jpg or .png file and click on save

#### To view anthologies:

1. You can access the anthologies you created under the mine tab on the dashboard anthologies menu
2. You can access the anthologies you were assigned under the assigned tab on the anthologies menu of the dashboard
3. You can access the anthologies index page by clicking on "See more anthologies" under the dashboard anthologies menu

#### To view an individual anthology

1. You can access the anthology of your choice either on the dashboard anthology menu or the anthologies index page "/anthologies" by click on it
2. On the anthology show you will be able to see the documents associated with that anthology

#### To remove an anthology from a document 

1. Click on remove from anthology under the anthology show page or under the documents index page 
2. In order to add an anthology to a document
3. Click on the add to anthology once you have selected the anthology from the select menu in the documents index page.

#### To assign a user to an anthology

1. Go to "/users" page 
2. Select the anthology you wish to add and select the user with the checkbox 

#### To search for a user

1. Type the firsname or last name or email of a user and click on search on the users index page
2. In order to remove a user from an anthology
3. Select the appropriate user from the users index page and click on remove from anthology (this is possible only if the user is already a part of the anthology)

**Comment by SteveMarvin** [comment]
1. I'm not seeing how one can remove a document from an anthology from the documents index page. 
2. Clicking on a user from the Users list causes an error:
![Screen Shot 2020-01-28 at 12 54 34 PM](https://user-images.githubusercontent.com/18423533/73291018-63ff5380-41cd-11ea-94aa-ce22eca3c31d.png), so cannot test removing user from anthology via user index page.
3. Search boxes are case-sensitive and return no results on an empty field

**Comment by jamiefolsom** [comment]
#2 is a bug -- good catch.
#3 is a worthwhile enhancement.

**Comment by jamiefolsom** [comment]
@timdunn22 have a look -- some feedback from Steve.
