### ISSUE TITLE
Search documents

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#158]
Necessary
- Search by title
- Search by author
- UI on document index view
- Emulate the tag ("Edition") filter http://studio.covecollective.org/documents?group=sr+project

**Comment by SteveMarvin** [comment]
Testing notes:
1. Case sensitivity is probably overkill for a search term
2. Title and Author will serve partial matches, but Editions won't...
3. Would probably be useful to be able to populate more than one search field at a time to further narrow searches
4. Does not support logical operators or wildcards
5. Searching on a blank field returns all documents

As it stands, search is working, but functionality is somewhat reduced by strict search terms and lack of operators or wildcards. Lack of partial term returns on Editions field is a serious issue.

**Comment by jamiefolsom** [comment]
@timdunn22, here are some requested refinements:

- [ ] Make title and author case-insensitive.
- [ ] Investigate how easy it would be to return results for partial editions tag matches.
