### ISSUE TITLE
Create an anthology

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#159]
- Create a new anthology model, with index, create/update (form), show views.
- Has many documents
- URL for anthology goes to index page
- Included documents have routes like `/anthology/:friendly_id/documents/:friendly_id`

**Comment by timdunn22** [comment]
This last part:
Included documents have routes like /anthology/:friendly_id/documents/:friendly_id
I think makes sense to do with the other issues involving adding documents to an anthology. I have put friendly ids on the anthology which work as well as the create/update/edit/index/show actions.

**Comment by SteveMarvin** [comment]
Can create, name, add description, add documents from documents page. URL goes to anthology index, has many docs, URL formatted with readable links. Can show and modify status.
