### ISSUE TITLE
As a teacher, I want to assign students to an anthology

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#162]
- An anthology has many students and a student has many anthologies (as a member) has_many_through (memberships) -- allows you to capture how the student has the anthology.
- Create a users index view, with checkboxes to select students to be assigned to an anthology, just like the documents index.
- Users index view should be visible only to teachers or admins (don't leak student info to students).
- Dashboard, users can see two tabs on the anthology widget: mine and assigned.

**Comment by timdunn22** [comment]
# Time Estimate 
5 -10 hours

**Comment by timdunn22** [comment]
@jamiefolsom This has already been completed.
