### ISSUE TITLE
Anthologies: Vetted Documents

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#167]
Add a boolean field to the documents model and table, and a checkbox to the document edit form, to allow editors to indicate that a document is: vetted or validated, for use in anthologies.

All vetted documents should be available to all in a new tab on the documents list, and be searched for using the document search feature.

**Comment by jamiefolsom** [comment]
Only admins can make documents vetted. @timdunn22

**Comment by jamiefolsom** [comment]
@timdunn22 more adjustments to be made to this feature, as noted in comment above.

**Comment by timdunn22** [comment]
# Time Estimate 
1-2 hours

**Comment by timdunn22** [comment]
# Testing
1. Login as a user which has an admin role
2. Click on Documents on the dashboard and then click on edit in the documents view
3. You should be able to see the vetted checkbox and update a document to be vetted
4. Login as a user which has no admin role
5. Click on Documents on the dashboard and then click on edit in the documents view
6. You should Not be able to see the vetted checkbox and update a document to be vetted
7. If you go the documents index page and perform a search you should be able to see the search results
8. On the documents index you should be able to see vetted documents (on the vetted tab)

**Comment by jamiefolsom** [comment]
Glad to see a test plan. Please add a URL for Steve's convenience, and please move the test plan to the PR, @timdunn22

**Comment by jamiefolsom** [comment]
@timdunn22 please fix this, put it back into Review/QA with a clear test plan (on the PR cover letter, if a PR is required), and then reassign to Steve.

**Comment by SteveMarvin** [comment]
Cannot see vetted checkbox

**Comment by SteveMarvin** [comment]
Can now see vetted checkbox, but both of my accounts are now admins, so I can't not see it :-D

**Comment by SteveMarvin** [comment]
I did manage to see all of this working as my accounts were in various stages, so I am going to accept this issue.
