### ISSUE TITLE
Anthologies: add guidance for banner dimensions

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#169]

**Comment by jamiefolsom** [comment]
@timdunn22 banner should be sized to fit within the anthology show view, and should have whitespace around it. Use CSS if possible, and add some guidance on the edit form, to help users upload an image of the correct dimensions. (~ 1000px wide)

**Comment by jamiefolsom** [comment]
This example works after a fashion because I scaled the image to 1000px wide before uploading, but still lacks appropriate spacing above/below/left and right.

<img width="1420" alt="Screenshot 2020-02-03 17 25 58" src="https://user-images.githubusercontent.com/882377/73696440-4e48cd00-46aa-11ea-9634-a6b31cc3478c.png">

**Comment by jamiefolsom** [comment]
@timdunn22 -- see comments on this issue above -- we should provide banner sizing guidance next to the upload form button.

**Comment by timdunn22** [comment]
# Time Estimate
1-2 hours estimate to make sure everything looks good.
