### ISSUE TITLE
Annotations: confirm annotation deletion

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#173]
Currently, clicking on the 'x' button on the annotation editor deletes the annotation. We should present a confirmation dialog to allow users to cancel deletion if that's not their intention.

**Comment by timdunn22** [comment]
# Time Estimate
- 2 hours

**Comment by jamiefolsom** [comment]
Modify this glyph sprite to show a trash can instead of an x for delete.

https://github.com/openannotation/annotator/blob/master/img/annotator-glyph-sprite.png

At very least, we need "are you sure" dialog to popup before deletion, and to return false, and cancel the deletion if user clicks no.

**Comment by jamiefolsom** [comment]
Closed by #237
