### ISSUE TITLE
Annotations: allow filtering by a specific user

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#174]
On this sidebar, it should be possible to filter annotations by a specific annotation author.

So a menu should appear at the top of the sidebar, under the "Who made them" heading, and above the "Me/Groups/Editions/All' buttons, which contains a list of all users who have access to this document, so that I can filter out all annotations except those made by a specific user.

This will either have to issue a new request to the annotation API, which specifies a user; or it will have to hide all annotations (already loaded), which do not have a specific value on their `user` field.

Refer to #152 for how to include only relevant users in the menu.

Refer to the "Me" button, and how that functions to see how to issue the correct API call, or to the "tag/category/visible portion" buttons for how to show/hide already-loaded annotations.

<img width="456" alt="Screenshot 2020-04-14 11 14 22" src="https://user-images.githubusercontent.com/882377/79241472-19db5500-7e41-11ea-9b08-99ac7c4a0332.png">

**Comment by timdunn22** [comment]
# Time estimate
2-4 hours

**Comment by jamiefolsom** [comment]
Closed by #306
