### ISSUE TITLE
As an editor, I want to link to COVE and BRANCH resources from documents in Annotation Studio

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#18]
Same media mgmt issues are present here as in #19.

**Comment by jamiefolsom** [comment]
If #32 (part COVE, part AS) is yes, that would allow images to be stored in COVE, and inserted in AS documents.

**Comment by jamiefolsom** [comment]
@SteveMarvin This is possible now -- if you can access an image on the web (eg on the COVE Editions website, but really, from anywhere), you can insert it into a  document in COVE Studio, in the editor, on a new document, for example, at: http://studio.covecollective.org/documents/new. Click "Paste or type directly into the form", and click the image insertion button, and you can paste an image URL into that field.

**Comment by SteveMarvin** [comment]
OK, then that's tested. I've been linking to online images left and right. ;-) 👍
