### ISSUE TITLE
Clicking on user from Users page causes error

### ISSUE THREAD

**Issue by SteveMarvin** [performant-software/Annotation-Studio#181]
![Screen Shot 2020-01-28 at 12 54 34 PM](https://user-images.githubusercontent.com/18423533/73291073-7c6f6e00-41cd-11ea-9940-804a41c1ded9.png)

**Comment by timdunn22** [comment]
I did not have this problem when checking on staging and locally. It may have been fixed in my commits after this.

**Comment by timdunn22** [comment]
# Time Estimate
1 hour

**Comment by jamiefolsom** [comment]
Appears to be fixed
