### ISSUE TITLE
Performance/stability on staging is bad

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#188]
And the application crashes, and won't come back up. We need to resolve this before deploying to production.

**Comment by timdunn22** [comment]
For this I have configured scout apm. I do get some insights from that however in order to go more in depth we would have to pay for that. So far as I can tell devise is very problematic but I need to dig deeper in order to be more sure as to why.

**Comment by jamiefolsom** [comment]
Ok, can you provision them paid tier of scout? I’ll do it if not.

**Comment by jamiefolsom** [comment]
I think this is fixed; it seems to have been an issue with asset compilation or serving -- now there is a problem with the home page cover image not showing, which I think is because it's specified by a config var. Have a look, @timdunn22. http://cove-staging.herokuapp.com/

**Comment by timdunn22** [comment]
When looking at the file system on staging there is no images folder anywhere and on staging the src url is referencing an images folder. Perhaps it's better to refer to an AWS bucket or another url in order to see the image.

**Comment by timdunn22** [comment]
I found the problem the home banner url referenced .jpeg instead of .jpg so I changed on heroku and now you can see the cover photo.

**Comment by jamiefolsom** [comment]
@timdunn22 please add steps to test for @SteveMarvin.

**Comment by SteveMarvin** [comment]
No testing steps. Moving to Rejected to get eyes on it.

**Comment by jamiefolsom** [comment]
@timdunn22 -- would you please add steps to test?

**Comment by timdunn22** [comment]
# Testing
1. Login to http://cove-staging.herokuapp.com/
2. Check if the cove logo shows up on login
3. Click around and make sure you are able to load pages in a timely fashion

**Comment by SteveMarvin** [comment]
Assuming the COVE logo is just the one in the footer...
![image](https://user-images.githubusercontent.com/18423533/78930937-f2683f00-7a72-11ea-87ef-9634e0c200c3.png)

Wood engraving doc: 21.79 s to load
The Double in Gothic Fiction 9.9o s to load
Blood in The Were-Wolf 11.53 s to load

Then after that the average time dropped to about 2-3 seconds, and remained reliably low for other docs on that page. 

Going into the Document page directly pushed the load time back up over 5 seconds, but never as bad as it was at first.

**Comment by timdunn22** [comment]
O sorry actually you will have to logout. Then if you can see the cove logo in the middle of the page that is what I was referring to.

**Comment by jamiefolsom** [comment]
Fixed by precompilation of assets.
