### ISSUE TITLE
Anthologies: user can only edit/delete his/her own anthologies

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#202]

**Comment by timdunn22** [comment]
# Time Estimate
2-4 hours

**Comment by timdunn22** [comment]
# Testing
1. Login and click on anthologies link on the dashboard
2. Click on the edit link of an anthology you did not create
3. You should see a message saying you can only edit anthologies that you own

**Comment by SteveMarvin** [comment]
This works, I can only see buttons for my entries, and can edit and delete them. However, attempting to create a new anthology throws an error. See: https://github.com/performant-software/annotation-studio/issues/216
