### ISSUE TITLE
Anthologies: permissions

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#205]
Admins and teachers can create anthologies and add docs and students; students can't.

**Comment by timdunn22** [comment]
# Time Estimate 
2 hours

**Comment by timdunn22** [comment]
# Testing
1. Login as a user that is an admin
2. Go to http://cove-staging.herokuapp.com/anthologies
3. You should see a link at the bottom to add an anthology
4.  Go to http://cove-staging.herokuapp.com/anthologies/ and click on any anthology
5. You should be able to add a document to an anthology
6. Login as a normal non admin non teacher user
7.  Go to http://cove-staging.herokuapp.com/anthologies
8.  You  should NOT see a link at the bottom to add an anthology
9.  Go to http://cove-staging.herokuapp.com/anthologies/ and click on any anthology
10. You should NOT be able to add a document to an anthology

**Comment by jamiefolsom** [comment]
@timdunn22 -- please copy (or move) your test plan to the PR. Thanks!

**Comment by SteveMarvin** [comment]
Need an admin account, cannot test

**Comment by jamiefolsom** [comment]
@timdunn22 here are the steps for creating an admin account for Steve:
- `heroku run rails c --app cove-staging` 
- `Apartment::Tenant.switch('cove-studio')`
- `admin_steve = User.new(email: 'steve+admin@performantsoftware.com', password: 'change', agreement: 'true')`
- `admin_steve.set_roles = ['admin']`
- `admin_steve.save`

Please do this for @SteveMarvin, and then write a rake task that makes this easy to do, for any user role, email address, password, etc.

**Comment by timdunn22** [comment]
Yes I know about that my question was about the NAVS account. Now you have to have a NAVS account to signin.

**Comment by jamiefolsom** [comment]
You're right -- I will create that account.

**Comment by jamiefolsom** [comment]
I've created that account, and sent a msg to @timdunn22 and @SteveMarvin on slack, to explain next steps.

**Comment by timdunn22** [comment]
@SteveMarvin So you should have an admin account now: Username is: steve+admin@performantsoftware.com and password is: something-secure-to-be-shared-via-slack

**Comment by jamiefolsom** [comment]
Password irrelevant here, since logging in via NAVSA, as long as @timdunn22 correctly modified role for new account.
