### ISSUE TITLE
Anthologies: on anthology show view, add document search and add feature

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#207]
It should be possible to search for documents by title or author on the anthology show view (eg: http://cove-staging.herokuapp.com/anthologies/literature-201-section-b), and from search results list (maybe in a separate tab), click a single button to add that document to an anthology.

Let's try the search fields at top, under banner.

**Comment by timdunn22** [comment]
# Time Estimate
5-6 hours
