### ISSUE TITLE
Enable multiple OAuth providers

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#209]
Likely one per tenant.

Once #243 is complete, move the config vars currently [stored in ENV](https://github.com/performant-software/Annotation-Studio/blob/master/config/initializers/devise.rb#L220-L224) to the per-tenant config, editable via the admin UI.

**Comment by timdunn22** [comment]
# Time Estimate
10 hours

**Comment by jamiefolsom** [comment]
Dupe of #259
