### ISSUE TITLE
Creating new anthology causes error

### ISSUE THREAD

**Issue by SteveMarvin** [performant-software/Annotation-Studio#216]
Attempt to create a new anthology causes error.

![image.png](https://images.zenhubusercontent.com/570d1074bf93871ccd994cd2/009595f1-db45-456e-a85b-3d6308dcc3fe)
The only thing in the console is this:
![image.png](https://images.zenhubusercontent.com/570d1074bf93871ccd994cd2/981fa3d6-519e-4f40-aca0-0fa254c8d407)

**Comment by jamiefolsom** [comment]
@timdunn22 please fix this, put it back into Review/QA with a clear test plan (on the PR cover letter, if a PR is required), and then reassign to Steve.
