### ISSUE TITLE
Add user management to anthology show view

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#220]
### What's the problem

It's hard to manage user access to anthologies.

### What's the solution

Currently it's possible to search for documents and add them to anthologies on the [anthology show view](http://cove-staging.herokuapp.com/anthologies/literature-201-section-b).

It should be possible to do the same for users. 

Let's add two tabs to the top of the list of documents; one shows the list of documents, the other, a list of users.

So here, where it says "Documents" at left, would BE a tab, next to another tab that reads: "Users".

![Screenshot 2020-04-22 14.25.16.png](https://images.zenhubusercontent.com/55c903e94f7a08fbb7f434a8/674984dc-87dc-4efd-8801-4d61b4a3a98a)

**Comment by timdunn22** [comment]
@jamiefolsom Is this an ok example of how we would want the nested tabs to look for the anthology 
<img width="1433" alt="Screen Shot 2020-04-27 at 20 48 14" src="https://user-images.githubusercontent.com/11293785/80387903-eed51480-88c8-11ea-9ee7-10121a4545db.png">

**Comment by jamiefolsom** [comment]
That looks fine, @timdunn22.
