### ISSUE TITLE
User filter menu should only include members of the Anthology rep_group

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#258]
Currently, it includes all members of all editions which have access to that document.

We add a new rep_group tag to docs and users, when they’re added to an anthology (the value is the anthology slug); only users with that tag should appear in the user filter menu when the document is loaded at its anthology URL.

**Comment by timdunn22** [comment]
@jamiefolsom Is this in reference to a route such as cove-staging/some-anthology/some-document?

**Comment by jamiefolsom** [comment]
These are the same document.

- http://cove-staging.herokuapp.com/documents/new-machine-stops
- http://cove-staging.herokuapp.com/anthologies/literature-201/documents/new-machine-stops

The second URL is the document when viewed from within an anthology.

When that document is accessed at the first URL, the user filter menu should show all users who are tagged with any rep_group that the document has been tagged with, _except_ the reg_group that matches the anthology slug.

When it's accessed at the second URL, the user filter menu should contain _only_ the users who are tagged with the reg_group that matches the anthology slug.

**Comment by SteveMarvin** [comment]
This seems to work fine, but I can't really tell which users are assigned to which rep groups. I will accept it, but this is not 100% tested.
