### ISSUE TITLE
Implement Shibboleth (SAML) with Devise, with config per-tenant

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#259]
We have an IdP to test against -- ping me when you are ready to start on this.

Here are some docs: 
- https://github.com/omniauth/omniauth-saml#devise-integration
- https://github.com/heartcombo/devise/wiki/OmniAuth:-Overview
- https://github.com/omniauth/omniauth-saml#usage
- https://madeintandem.com/blog/configuring-rails-app-single-sign-saml-multiple-providers/
- https://blog.cloud66.com/adding-sso-to-your-rails-application-with-saml/

**Comment by timdunn22** [comment]
@jamiefolsom 
## What needs to be completed on this issue?
1. SSL has to default to SSL whenever the user loads a page.
2. SSL has to work on the annotation api side as well eg. loading annotations.
3. SAML config in devise has to be changed to reflect an ability to switch between OAuth and SAML (I was just trying to get SAML to work before)
4. The user should be able to put the certificate and key information related to SAML and OAuth in the admin portal. (Now they can just select which one they want)

**Comment by jamiefolsom** [comment]
@dleadbetter for each tenant to authenticate against a different IdP, we'll need to make it possible to publish distinct per-tenant metadata files at the `/sp/metadata` route.

**Comment by dleadbetter** [comment]
@jamiefolsom - This should be completed in #282. See [this](https://github.com/performant-software/Annotation-Studio/pull/302/commits/2d0eae88ba8dd07b3af6579220dc98121f74c563) diff. The route will be the same for all tenants (`/sp/metadata`), but the XML file rendered will be defined in the `config/domain_specific/config.yml` file.

**Comment by jamiefolsom** [comment]
Ah, great @dleadbetter, indeed it is, thanks for clarifying.

**Comment by jamiefolsom** [comment]
Closed via #302
