### ISSUE TITLE
Copyright notice incomplete

### ISSUE THREAD

**Issue by SteveMarvin** [performant-software/Annotation-Studio#285]
You have to include the mark, the date and the holder of the copyright. I don't think this is complete.

![image.png](https://images.zenhubusercontent.com/570d1074bf93871ccd994cd2/5db53966-dd65-4edc-ab48-e81cb34a60bc)

**Comment by jamiefolsom** [comment]
@timdunn22 `© 2020 COVE Collective`

**Comment by jamiefolsom** [comment]
Closed by #306
