### ISSUE TITLE
Notify users when they try to download a csv with no annoations

### ISSUE THREAD

**Issue by timdunn22** [performant-software/Annotation-Studio#294]

**Comment by jamiefolsom** [comment]
Closed by #300

**Comment by jamiefolsom** [comment]
@timdunn22 -- this is not working correctly -- it appears to say there are no annotations to be downloaded, when there are. Check both anthologized documents, and non-anthologized docs. See: https://studio.covecollective.org/anthologies/engl-202-fall-2020/documents/gods-grandeur-e808ea9b-d9df-43a8-9ec3-a5cf98a6310c
<img width="1537" alt="image002 (2)" src="https://user-images.githubusercontent.com/882377/97357338-fa9d9580-186f-11eb-93f9-e02cec0790c4.png">
