### ISSUE TITLE
As an editor, I want to download a document for use within a COVE edition, or elsewhere

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#3]
While possible, this story takes a back seat to #30.

Options, roughly in order of sequence might include: 
- [ ] HTML file
- [ ] Jekyll post >> github repo, with front-matter
- [ ] PDF
- [ ] ePub
- [ ] Word, RTF

**Comment by SteveMarvin** [comment]
Only option available is HTML, but this is working.
