### ISSUE TITLE
PDF Upload Help Text

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#301]
Under the PDF upload feature, add the following to the existing help text, which reads: "This feature converts your documents for use within Annotation Studio, and strips out all formatting. Simple, single-column documents work best." 

"For a PDF upload to work, the file must include a text layer before it's uploaded. You can add a text layer before uploading by running your PDF through an OCR tool like Abbyy FineReader or Tesseract."

**Comment by jamiefolsom** [comment]
Closed by #303

**Comment by sarastanton** [comment]
@jamiefolsom seems like this one might already be done?
  
![Screen Shot 2021-01-14 at 4.22.43 PM.png](https://images.zenhubusercontent.com/5e82012bbfb4ae044d992cfa/71faae3b-53c5-41de-8607-484421210d51)
