### ISSUE TITLE
Internal URLs show error if not logged in

### ISSUE THREAD

**Issue by SteveMarvin** [performant-software/Annotation-Studio#305]
If the user tries to go to an internal URL like https://staging.covecollective.org/dashboard without already being logged in, rather than putting the user through login and then redirecting, it says the page does not exist.

![image.png](https://images.zenhubusercontent.com/570d1074bf93871ccd994cd2/20e845b5-654a-4f66-af13-795a09badaf9)

**Comment by SteveMarvin** [comment]
This is still happening. Perhaps because I am logged in through NAVSA?

**Comment by jamiefolsom** [comment]
@timdunn22 -- can you fix this? Appears to be the same issue, or similar to, #242
