### ISSUE TITLE
User/Group Filter Behavior

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#307]
- Clicking Me/Teams/Editions should set the User filter menu to "All Users", and should issue a query to the API with `mode=group` for Teams or `mode=class` for Editions (or `mode=user`, ONLY if "Me" is clicked).
- Selecting a specific User from the User filter menu should issue a request to the API with `mode=user` and `user=[email-of-user-selected]`, and unselect all Me/Teams/Editions filter buttons above.
- Selecting "All Users" User from the User filter menu should issue a request to the API with `mode=class`, and set the "Editions" button to selected. This is identical to selecting "Editions" from filter button menu.

**Comment by SteveMarvin** [comment]
👍

**Comment by jamiefolsom** [comment]
Closed by #313
