### ISSUE TITLE
"Save document for export" not working

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#312]
Freezes on ‘creating snapshot’ -- see errors in js console.

404s for user.json, etc when using `/anthologies/` URL; 500 errors on the `/documents/` URL

https://github.com/performant-software/Annotation-Studio/blob/master/config/routes.rb#L52

https://github.com/performant-software/Annotation-Studio/blob/master/app/assets/javascripts/snapshot.js#L64

**Comment by SteveMarvin** [comment]
No errors on saving  snapshot
