### ISSUE TITLE
Document Edit Form: Date doesn't save

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#322]
Convert this to a string field.

**Comment by SteveMarvin** [comment]
Sara wants to look at a more flexible entry criteria for this field, so moving to rejected

**Comment by sarastanton** [comment]
The database migration was still pending in Staging - fixed now. This is ready for another look, @SteveMarvin - thanks!

**Comment by jamiefolsom** [comment]
Great, good to deploy this to production as well, @sarastanton !
