### ISSUE TITLE
Document upload/conversion not working

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#334]
From PDF at least:

![image](https://user-images.githubusercontent.com/882377/109349218-9998c500-7843-11eb-9581-c9f75351a815.png)

**Comment by sarastanton** [comment]
@jamiefolsom The document conversion is handled by a Delayed Job worker - I think this is the issue:

<img width="715" alt="Screen Shot 2021-03-06 at 1 40 17 AM" src="https://user-images.githubusercontent.com/20568337/110199244-27b11480-7e1d-11eb-9c41-b51ae9553dbe.png">

**Comment by sarastanton** [comment]
Manually setting a JVM buildpack (`heroku/jvm`) in Heroku resolved this issue. PR #365 handles styling of line breaks in newly uploaded documents.

**Comment by jamiefolsom** [comment]
Great! Let's do that both for staging and production, if you haven't already -- I've approved #365, so let's go ahead and deploy that to production at your convenience. Nice work!
