### ISSUE TITLE
Teachers and students need access to the annotation CSV export feature

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#336]
Note: teacher is a role; currently only the admin role has access to that feature.

**Comment by sarastanton** [comment]
Steps to test:
1) Log in as a user with a "teacher" or "student" role
2) Select a Document from the Document index (https://cove-staging.herokuapp.com/documents)
3) When viewing selected document, the Annotations sidebar on right-hand side of page should include "Download CSV" button
4) Clicking "Download CSV" button should generate a CSV file of annotation data for that particular document
