### ISSUE TITLE
Document preview is not working

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#337]
Probably on anthologized documents, but should clarify first.

![image](https://user-images.githubusercontent.com/882377/109349063-59394700-7843-11eb-91e6-c5cfc0712a8f.png)

**Comment by sarastanton** [comment]
It looks like the issue occurs when the 'Preview' button is clicked for a document that has no saved snapshot. I'm thinking the best solution is to disable the 'Preview' button if there is no saved snapshot (and add a bit more detail to the helper text to help the user understand why it's disabled).
