### ISSUE TITLE
Allow management of users via /admin

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#340]
I believe this would just require adding: 

- A "confirmed" checkbox to confirm the user, and
- An "agreement" checkbox to indicate acceptance of the EULA
- A password field to allow setting of the user password.

UPDATE 8/25:

Also: please investigate how much work it would be to allow `User` accounts which are marked with an `admin` role to access the `/admin` route, instead of, or in addition to, requiring users to also have an `AdminUser` account, which is currently the case, and somewhat confusing.

Alternatively, I suppose we could create an `AdminUser` when a `User` is assigned to the admin role.

**Comment by sarastanton** [comment]
Added new fields (`password` ,`password_confirmation`, `roles`, `agreement`, `confirmed_at`) - leaving open for second piece (granting access to admin role users, rather than `AdminUsers`)
