### ISSUE TITLE
Set up NASSR Tenant

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#346]
- Staging and Production
- Tenant in database
  - OAuth (maybe)
  - SAML Maybe
- Document process
  - Determine where config vars live
  - DNS on heroku
  - DNS on domain
- Admin users set up; do through console for now (see #340).

**Comment by sarastanton** [comment]
OAuth setup pending

**Comment by jamiefolsom** [comment]
@sarastanton -- once #338 is complete, take this one on next -- I think NASSR is going to use Okta as a SAML IdP, but I will put you in touch with them to confirm. Then you would set up the NASSR tenant to use SAML auth with that IdP.
