### ISSUE TITLE
Document doesn't complete loading

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#348]
If you go to the document below at Purdue COVE, you get that spinning wheel. The document lets me annotate but the spinning wheel never disappears. I have never seen this behavior before. Any idea? See image below. I just checked again and that’s still happening at Purdue COVE:https://purdue.covecollective.org/documents/a-far-cry-from-africa-68e20e15-e489-421b-a91d-e9b73290df8e

**Comment by sarastanton** [comment]
This might be resolved - unable to reproduce as of 3/5/21, specified document loads fine, no spinning wheel

**Comment by SteveMarvin** [comment]
Works on my machine

**Comment by jamiefolsom** [comment]
Closing as unable to reproduce.
