### ISSUE TITLE
Implement unique Google Analytics codes per-tenant

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#349]
This is currently an application-wide setting -- config var in Heroku, should be moved to the tenant model in the database.

**Comment by sarastanton** [comment]
@SteveMarvin  To test:

- 'Google Analytics code' form field should be present on the Tenants tab of the ActiveAdmin dashboard at https://staging.covecollective.org/admin/  
- The value in this field should appear in the html (head and script tags) of that particular tenant's staging site (i.e. https://colum-staging.covecollective.org/ for Columbia College Chicago) in the following places:
![Screen Shot 2021-08-17 at 8.46.24 AM.png](https://images.zenhubusercontent.com/5e82012bbfb4ae044d992cfa/b19d99dd-78c5-440c-9f23-69dae527dfb7)
