### ISSUE TITLE
As a reader, I want important content from annotation text included in the snapshot

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#35]
Like comments, links, images and image attributes, etc, e.g: `<p><a class="catalog-popup" href="catalog/image/event:26" data-parent="" data-gallery="remoteload" data-title="Battle of Hampton Roads"><img src="http://s3.amazonaws.com/sites-mel-catalog.herokuapp.com/images/images/000/002/569/thumb/1280px-The_Monitor_and_Merrimac.jpg?1468592161" alt="" /></a></p>`

**Comment by SteveMarvin** [comment]
Annotations included within HTML metadata of snapshot

**Comment by jamiefolsom** [comment]
Closed by #31

**Comment by SteveMarvin** [comment]
Regression: not visible in Preview, but is in HTML metadata
