### ISSUE TITLE
When filtering annotations by a specific user, only group-visible annotations should be loaded

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#353]
Apparently, when using the single-user filter, Studio shows all annotations by that user, regardless of the visibility toggle, or group membership, to the viewer.

The single-user filter should respect the group visibility toggle. NB: appear this might be due to the `mode: user` parameter in the query.

**Comment by SteveMarvin** [comment]
Nope, I'm afraid that I can still see annotations marked as NOT visible to group. Just to make sure I have this straight, here is my test setup:

Log in as admin.
DOC: https://staging.covecollective.org/documents/the-machine-stops-for-the-game
Switch user to ANNE NAGEL
Filter by User KAARI NEWMAN
I now see two annotations. One that says "this should also be visible" which is the one marked for group visibility
I also see "this should not" which is the note marked for NO group visibility.
