### ISSUE TITLE
Disable "Download HTML" when there's no snapshot saved

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#367]
Same as #337, but for the "Download HTML" button. 

~An alternative would be to invoke the "Save Document"/snapshot feature if/when either preview or download are clicked. Ping me before implementing to discuss.~ (not doing this for now -- just disable the download button when there's no HTML snapshot to download)

**Comment by sarastanton** [comment]
Per our discussion, going to go with the same approach (i.e. disable button unless saved snapshot exists) used for #337
