### ISSUE TITLE
Add NASSR to the list of associations to nav bar

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#394]
Next to NAVSA | BAVS | AVSA | **NASSR**

Link to: https://www.nassr.ca/

Also: the nav bar should resize gracefully when the viewport width doesn't allow the brand and those links all to show.
- Keep the nav on a single line
- Add a hamburger menu for links if necessary
- Brand can be hidden if need be
- Be sure that navigation links below the nav are not concealed on narrow browser viewports (as is currently the case).

<img width="859" alt="Screen Shot 2022-03-11 at 16 53 14" src="https://user-images.githubusercontent.com/882377/157975637-db296465-fad6-4f98-ba9c-ff4cde287887.png">

**Comment by mythmakerseven** [comment]
Done in https://github.com/performant-software/Annotation-Studio/pull/400
