### ISSUE TITLE
As an anthology owner, I want to select multiple documents at once for addition

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#414]
The ability to batch select titles when you create an anthology; now, you have to pick one title at a time.

**Comment by camdendotlol** [comment]
It looks like `anthology_add` already supports adding multiple documents: https://github.com/performant-software/Annotation-Studio/blob/master/app/controllers/documents_controller.rb#L14

So, assuming that code works as expected, this change should only require updates to the view.

This options field, located in `app/views/anthologies/_searched_documents.erb`, should get a new button labeled "Select".
![Screen Shot 2022-06-23 at 10 48 58 AM](https://user-images.githubusercontent.com/64725469/175330487-afe51a51-8ff4-450f-8041-525c5a18efbd.png)

Then there should be a button below the table (or maybe above?) labeled "Add Selected". This would call `anthology_add_path` and pass all the selected documents' IDs.

Estimate: 6 hours
