### ISSUE TITLE
As an anthology owner, I want to create subfolders within an anthology

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#416]
Add the ability to create subfolders within your anthology. This would allow users to organize their reading lists better. Now, we rely on sorting alphabetically. 

Question for Dino: How would he want it to affect URLs? We could either have this be a visual organizing mechanism for the anthology document list only, and not affect URLs, or we could have it create new URLs for documents that are in folders, like:

Document in Anthology but not in folder:

`/anthologies/:anthology_slug/:document_slug`

Document in Anthology and in folder:

`/anthologies/:anthology_slug/:folder_name/:document_slug`

**Comment by camdendotlol** [comment]
This would need to start with some work on the database.

There would be a new model called `DocumentFolder`, along with a join table connecting `DocumentFolder`, `Document`. `Anthology` has many `DocumentFolder`s, and `Document` and `DocumentFolder` have a many-to-many relationship. 

This modeling is fairly complex and will take some time, but once it is implemented, the relevant views shouldn't be too hard.

Estimate: 24 hours
