### ISSUE TITLE
Site does not redirect when not logged in

### ISSUE THREAD

**Issue by SteveMarvin** [performant-software/Annotation-Studio#42]
If I try to navigate to a bookmarked page within the site without having logged in already, I am told the page does not exist, instead of being redirected to login.

**Comment by jamiefolsom** [comment]
@SteveMarvin is this still the case with http://cove-staging.herokuapp.com/ and http://dev-rc-distro.pantheonsite.io/?

**Comment by SteveMarvin** [comment]
Nope, looks good now. Closing this. 👍
