### ISSUE TITLE
Cannot multiselect to remove docs from anthology page

### ISSUE THREAD

**Issue by SteveMarvin** [performant-software/Annotation-Studio#421]
on the anth page, one can multiselect, but the multiselect action button says "Add selected", which does nothing. It should probably be "remove selected"
![image](https://user-images.githubusercontent.com/18423533/177368155-7ba362ac-d13a-47ba-81da-f769f24b7b45.png)

**Comment by camdendotlol** [comment]
Actually, this was addressed in #423 so stalebot was correct in closing it
