### ISSUE TITLE
Selections from MEL catalog are not attaching text

### ISSUE THREAD

**Issue by SteveMarvin** [performant-software/Annotation-Studio#43]
If I select a book from the catalog, the document creation fields are filled out for me, but the main body text is not attached to the document. When I create, it says the document was created, but there is no text.

**Comment by jamiefolsom** [comment]
Hi @SteveMarvin MEL Catalog to be removed from this instance, at least for the short term. Keeping this issue open to track that step.

**Comment by jamiefolsom** [comment]
MEL Catalog has been disabled on production.

**Comment by SteveMarvin** [comment]
True dat. 👍
