### ISSUE TITLE
Not authorized to view my preview

### ISSUE THREAD

**Issue by SteveMarvin** [performant-software/Annotation-Studio#44]
When I take a snapshot of my document, and attempt to preview it, I am returned to my dashboard and told that I am not authorized to access this page.

**Comment by jamiefolsom** [comment]
Hi @SteveMarvin, your account should now have permission to view your preview. I will make it so non-permitted users don't see that button, and will keep this issue open to track it. Thanks!

**Comment by jamiefolsom** [comment]
@SteveMarvin a note to let you know that accounts on http://studio.covecollective.org/ will be carried back into staging and from there into review apps. So if you create an account there, and let me know, I will grant you the permissions you need there, and from then forward, you should not run into these issues. Thanks!

**Comment by SteveMarvin** [comment]
Regression: able to view my preview.
