### ISSUE TITLE
Set max height and overflow scrolling on folder grid

### ISSUE THREAD

**Issue by camdendotlol** [performant-software/Annotation-Studio#440]
The grid of folder icons should have a maximum height and should be scrollable if it exceeds that height. This would allow the folder feature to support dozens or hundreds of folders without taking too much space.

**Comment by sarastanton** [comment]
Hi @SteveMarvin , this is ready to be looked at now (https://staging.covecollective.org/) - steps for testing are listed in the [PR](https://github.com/performant-software/Annotation-Studio/pull/445). Thanks!
