### ISSUE TITLE
As a reader, I want to be able to view a single annotation

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#46]
On http://dev-rc-distro.pantheonsite.io/node/3201 for example.

While reading, clicking on a highlight should display all annotation metadata, including:
- [ ] Quote
- [ ] Text, with images, links, etc
- [ ] Annotator name
- [ ] Tags
- [ ] Category(ies)

**Comment by SteveMarvin** [comment]
Regression: seeing all entered metadata
