### ISSUE TITLE
Deliver ribbon markup and code to David for reference on COVE

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#55]

**Comment by SteveMarvin** [comment]
Not sure how I can test this. :-)

**Comment by jamiefolsom** [comment]
Good point @SteveMarvin -- sorry about that.

Have a look at: 
- http://cove-staging.herokuapp.com/ and
- http://test-rc-distro.pantheonsite.io/

They should share the same (or similar) black nav ribbon at top.

Thanks!

**Comment by SteveMarvin** [comment]
Well, I'm not sure if it's meaningful, but the ribbons are a little different. The heroku site bar looks like this:
![screen shot 2016-09-15 at 10 34 32 am](https://cloud.githubusercontent.com/assets/18423533/18553823/0398b3c2-7b30-11e6-8ba2-cde7690a7cc5.png)

with a Register link and the boxed arrow next to Cove Editions, while the pantheonsite bar looks like this:

![screen shot 2016-09-15 at 10 33 23 am](https://cloud.githubusercontent.com/assets/18423533/18553854/24e3e754-7b30-11e6-83e2-f93799d1c7ac.png)

with no Register link and the boxed arrow next to Cove Studio. This qualifies as "similar", but not "the same" according to the test criteria given me. :trollface:

**Comment by daverett** [comment]
Correct me if I’m wrong @jamiefolsom, but I think the Login and Register links can be different, though the background for the active site link is gray in AS and black at the COVE. That should probably be consistent. Also, I'm noting some issues on both sites in Safari where the NAVSA logo breaks to another line--probably some margins and/or padding that need to be adjusted.

**Comment by SteveMarvin** [comment]
Confirmed. Line break with logo does not occur on latest Firefox or Chrome, but does on Safari for both sites.
![screen shot 2016-09-15 at 11 21 23 am](https://cloud.githubusercontent.com/assets/18423533/18555646/94d18ef8-7b36-11e6-9d8e-7592db8a66c4.png)

**Comment by SteveMarvin** [comment]
Fonts also vary slightly...I figured they also fell into the "similar" category. Should they conform also?

**Comment by akstuhl** [comment]
Just a note that the "Register" dropdown is removed from the nav bar in #74

**Comment by jamiefolsom** [comment]
@SteveMarvin very helpful, thanks. @daverett I will do some tweaking on AS, and provide you with some updated CSS once I have it working. Would be good to be using the same fonts and colors throughout. We can discuss today with Dino.

**Comment by SteveMarvin** [comment]
Oops, I should have moved this out of Delivered to avoid the following question...has this been worked on since this discussion?

**Comment by jamiefolsom** [comment]
Hi @SteveMarvin -- it has not, I think we'll wrap it up once the SSO functionality gets merged and deployed.

**Comment by jamiefolsom** [comment]
@daverett, what do you think, should we use that light gray background, like on studio, to indicate "you are here"? And helvetica-neue for the type face?

**Comment by daverett** [comment]
@jamiefolsom and @SteveMarvin, I believe I have these matched now with Helvetica Neue, gray background for "active" links, and a few other small differences I noted. Agreed?

**Comment by jamiefolsom** [comment]
Looks good to me (comparing http://dev-rc-distro.pantheonsite.io/ to http://cove-staging.herokuapp.com/), thanks @daverett.

**Comment by jamiefolsom** [comment]
@SteveMarvin want to check on this again for us?

**Comment by SteveMarvin** [comment]
Minor font variations, no real discrepancies.

There is also a small arrow by the login link on the cove-staging site, but this makes sense, as there is a NAVSA login option there that is not present on the test-rc site.
