### ISSUE TITLE
Improper closure when both side panels are opened.

### ISSUE THREAD

**Issue by SteveMarvin** [performant-software/Annotation-Studio#58]
When you are in document view, and open both side panels simultaneously, when you click within the document body, both panels close. However, the one that was opened first has a kind of "precedence", and when it slides closed, it drags the other closed in the same direction. Thus, if I open the right panel first, and then the left, when I click in the document body, the right panel closes by sliding off to the right properly, but the left panel closes by sliding into the center of the screen, as it is "dragged" off by the closing left panel. Once dragged into the center of the screen, the panel closes, so there is not a functionality bug here, just an aesthetic one.
![sidebar_center](https://cloud.githubusercontent.com/assets/18423533/18094645/34ad093a-6ea2-11e6-8434-44026a420a1a.png)

**Comment by jamiefolsom** [comment]
Hi @SteveMarvin, yeah, I see what you mean, and that is not optimal. Not sure when I'll get to this one.
