### ISSUE TITLE
document conversion requires a refresh

### ISSUE THREAD

**Issue by SteveMarvin** [performant-software/Annotation-Studio#59]
When I have uploaded a new document, and open it for the first time to annotate it, I am given the message: "Please wait. The document is being converted." That's all good, but the message never goes away. It requires a manual refresh by the user to see the document. If the document is not going to refresh automatically when the conversion is done, the page should at least advise the user "Please refresh the screen after a few moments."

**Comment by SteveMarvin** [comment]
Language has not been changed...bump.

**Comment by jamiefolsom** [comment]
This should be corrected, but it's not urgent.
