### ISSUE TITLE
Add SSL Cert to COVE site

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#62]
- See: https://pantheon.io/docs/enable-https/
- @akstuhl is going to lead on this effort; @daverett can help

**Comment by jamiefolsom** [comment]
Hey @akstuhl if this is unnecessary for staging, let's move it to the icebox. We can determine later if it's essential before launch. Sound good?

**Comment by daverett** [comment]
For dev and staging, Pantheon provides SSL certs out of the box. Once production becomes necessary, that will be a different story. But I think we can kick that can for now, yes?

**Comment by jamiefolsom** [comment]
@daverett agreed!
