### ISSUE TITLE
As a student, I want to be able to join navsa to get access to AS

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#63]
Add a new member level to navsa.org for students, which will allow them to access AS and COVE

**Comment by SteveMarvin** [comment]
I see the student level on the join-navsa page. I can't verify that it does result in a student membership without paying, but I have high confidence that it will do so. 🎅 

I'm going to mark this as accepted, unless we want to provide me with fake payment info.
