### ISSUE TITLE
Screencast: COVE 2.0 Overview

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#64]
1. Project overview
   - Introduction
     - This will be a quick overview, with detailed how-to videos to follow
     - We're in the middle of development, so some things will change
   - Priorities
     - Ease of use
     - Single-purpose spaces for activities
     - Enable integrations with other systems
     - Work products portable, durable and independent of tools of production.
   - Navigation
     - Top nav bar
     - Single Sign On (coming soon)
   - Features
     - All features previously available via "in-COVE" annotation
     - Features are organized somewhat differently
       - Production of edition documents happens in AS
       - Consumption of edition documents happens in COVE
   - Architecture
     - Three systems, integrated; 
       - NAVSA for sign-on
       - COVE for assembling and presenting editions
       - AS for annotating documents for inclusion in editions
     - Future possibilities

**Comment by jamiefolsom** [comment]
Completed and [delivered](https://www.dropbox.com/s/9f3nt2mm8mso6pv/COVE%20Screencast%201%3A%20Overview.mp4?dl=0)

**Comment by SteveMarvin** [comment]
ACCEPTing this at this stage...
