### ISSUE TITLE
Screencast: COVE Studio Intro

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#65]
This screencast will show you how to:
- Create an account
- Add "edition" and "team" tags to your account
- Get the editorial permissions you need (by contacting an admin)
- Add edition tags to documents to share them with other editors
1. Create an account
   - Visit `https://studio.covecollective.com`
   - Click "Log in" at top right
   - Log in via navsa or login/create a non-navsa account
2. Add tags to your account
   - Visit `https://studio.covecollective.com/users/edit`
   - Add a tag or two to the "Editions" box, and hit enter
   - Click "Update' at the bottom of the form.
3. Get permissions
   - Send email to jamie@performantsoftware.com from the email account you used to sign up with COVE Studio
   - Request editorial permissions to manage documents
4. Add edition tags to documents to control visibility
   - Visit `https://studio.covecollective.com/documents`
   - Click Edit at the far right of a document in the list 
   - At bottom right, enter the name of an edition you added to your own account and hit enter
   - Click "Update Document" at the bottom

**Comment by jamiefolsom** [comment]
This will have to be broken out into several screencasts to keep them under 3 minutes each.

**Comment by jamiefolsom** [comment]
Breaking out document and user tagging as a separate issue.

**Comment by jamiefolsom** [comment]
@SteveMarvin I think this has all been covered in the various screencasts.

**Comment by jamiefolsom** [comment]
You've previously reviewed my screencasts, and I believe at least provisionally accepted them, so I think we're done with this epic, with the caveats, both stylistic and substantive that you noted. Given that this entire effort was out of scope, and that they didn't complain about those qualitative issues with the videos, I am inclined to say we should close these out if you're OK with that.

**Comment by SteveMarvin** [comment]
Definitely. My comments were not disqualifying, merely suggestions for consideration in future efforts. And since, as you say, these were both out of scope and for limited distribution, they're probably not worth the effort in doing even in future. Ship it! 👍
