### ISSUE TITLE
Screencast: Annotation Studio: Viewing and Filtering Annotations

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#67]

**Comment by jamiefolsom** [comment]
[This screencast](https://www.dropbox.com/s/j829fvb2rjxbuo6/COVE-2-Viewing-Filtering.mp4?dl=0) partially completes this issue as it was originally phrased. I am adding [#79] to cover the activities that didn't fit, which is most of them.

**Comment by SteveMarvin** [comment]
This looks good to me. 👍  

I'm assuming that super nit-picky critiques like slight variability in audio leveling and vocal hesitations aren't worth noting for the intended usage of this delivery...?

**Comment by jamiefolsom** [comment]
Hi @SteveMarvin -- those are good catches. I am refining my process in producing these, but audio remains a bit rough. With time a bit tight, I am going to agree with you that they're not enough to warrant a redo in this case, but I will try to improve them in future screencasts. Thanks!
