### ISSUE TITLE
Screencast: Annotation Studio: Export to COVE

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#68]
This screencast explains how to:

- Snapshot, Preview a document
- Export to HTML
- Export to COVE Editions

https://drive.google.com/open?id=0B4r_9zFhjag8OUt6LVdYdFo4T3c

**Comment by SteveMarvin** [comment]
Kind of like the last one: Saying "I can click this and see this, or click that and see that..." but not actually clicking and demonstrating is a very odd choice to make in a demonstration video. You want them to see what you are describing, not imagine it. 

I would advise going back through and anywhere you say that a user CAN do something, do it and demonstrate it.
