### ISSUE TITLE
As an editor, I want to import texts and make them available to annotators of my choosing

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#7]
I want to: 
- [x] Upload word documents, PDFs, text files, HTML, etc
- [x] Convert them to a common annotatable format (HTML)
- [x] Continue to edit them to add in chapters, sections, formatting, media, etc
- [x] Store them and mark them as visible to specific groups of annotators
- [x] Optionally mark them as publicly visible without login
- [x] Temporarily archive or permanently delete them if I no longer want to use them

**Comment by jamiefolsom** [comment]
Closed by deployment of AS to: https://cove-studio.herokuapp.com/

**Comment by SteveMarvin** [comment]
- Uploaded documents never convert #102 
- Not clear how to "Optionally mark them as publicly visible without login"
- No way to delete documents
