### ISSUE TITLE
account confirmation link goes to localhost

### ISSUE THREAD

**Issue by SteveMarvin** [performant-software/Annotation-Studio#77]
http://localhost:5000/users/confirmation?confirmation_token=T5Ejd-sJeJ_WVQ7SguAh

It was a signup at cove-studio.herokuapp.com. That may not have been a valid place to test, but I was trying to create a usable test account for COVE. The signup seemed to work, and I was sent a confirmation email, but the confirmation link was as above.

**Comment by jamiefolsom** [comment]
Should be corrected on http://studio.covecollective.org/

**Comment by SteveMarvin** [comment]
Regression: new signup successful, confirmation link valid.
