### ISSUE TITLE
As a user, I want to add comments, media, categories and control visibility of my annotations

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#79]
## How to test

1. Log in at http://cove-staging.herokuapp.com
1. Go to http://cove-staging.herokuapp.com/documents/example
1. Select text, click the annotator button, and use the editor to add comments, categories, tags, link, images, and control permissions on the annotations. See Screenshot. NB: ignore the two MEL cat buttons at the right end of the second row on the editor toolbar. Use the link and image buttons on the left end of that same second editor toolbar row.

![screenshot 2016-11-08 09 39 27](https://cloud.githubusercontent.com/assets/882377/20103286/5565d996-a597-11e6-9554-220df5098231.png)

## Description
As an annotator, I want to add content, settings and metadata to my annotations.
- Comments
- Tags
- Categories
- Media, links
- Permissions

**Comment by SteveMarvin** [comment]
All working as advertised. 👍
