### ISSUE TITLE
Discrepancies between staging and production

### ISSUE THREAD

**Issue by SteveMarvin** [performant-software/Annotation-Studio#93]
This epic is to list discrepancies between what is on staging at http://cove-staging.herokuapp.com/ and what is on production at tudio.covecollective.org. Stories within this epic will be individual bugs detailing specific discrepancies.

**Comment by jamiefolsom** [comment]
Hey @SteveMarvin, this is great! One note -- the final deploy to prod hasn't happened yet, so it would be too soon to launch into this with gusto. I hope to have it done this afternoon though!

**Comment by SteveMarvin** [comment]
Whoops! OK. 

I confess I am loving the idea of an Epic of bugs. Warms the cold cockles of my tester heart.

**Comment by jamiefolsom** [comment]
Love it, and it makes my blood run ice cold in my veins. 😜
