### ISSUE TITLE
CSS: Poem Stage Direction Line Height is 0

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#95]
CSS: Poem Stage Direction Line Height is 0

**Comment by jamiefolsom** [comment]
Fixed. See: studio.covecollective.org/documents/manfred-a-dramatic-poem

**Comment by SteveMarvin** [comment]
I seem to have been de-adminned. I am not authorized to see this page. steve@performantsoftware.com

**Comment by SteveMarvin** [comment]
Sorry, was able to access by adding the editors tag to my profile. I do see stage directions...the line height does not appear to be zero. ;-) 👍

**Comment by jamiefolsom** [comment]
And you're re-adminned. 😄
