### ISSUE TITLE
XML errors in many of the "All" documents

### ISSUE THREAD

**Issue by SteveMarvin** [performant-software/Annotation-Studio#99]
Jamie mentioned this is a bad URL...get this when trying to view something posted to COVE...

![image](https://cloud.githubusercontent.com/assets/18423533/21153024/cc54db6e-c136-11e6-9b0e-ab113177d513.png)

**Comment by jamiefolsom** [comment]
Dupe of #109 I think -- to your point about it being intermittent, I believe it's only for new snapshots that it's fixed, but once a document has been resnapshotted once, the XML should never recur.

**Comment by SteveMarvin** [comment]
OK, Accepting then. 👍
